version: '3.8'

services:
  node-18:
    image: node:18

  detain:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # network_mode: "host"
    container_name: detain-dev
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - 5174:5172
    volumes:
      - ./:/app
    tty: true
    stdin_open: true
    restart: on-failure
